# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VuqsuonMdJJaGjBzaSSz8U7Doi3kG0Xu
"""

!pip install transformers

from google.colab import drive
drive.mount('/content/drive')

!tar -xzvf /content/drive/MyDrive/myProjects/cv-corpus-12.0-delta-2022-12-07-en.tar.gz -C "test"

import librosa as lr
def LoadAudio(x):
    x, sr = lr.load(x, sr=16000)
    return x

from transformers import pipeline
pipe = pipeline(model="Tesseract3D/LMT2-Tuned-S")  # change to "your-username/the-name-you-picked"

def transcribe(audio):
    text = pipe(audio)["text"]
    return text

import pandas as pd
import numpy as np
from tqdm import tqdm

df = pd.read_csv('/content/test/cv-corpus-12.0-delta-2022-12-07/en/validated.tsv', sep="\t")

# read the data frame
df.head()

inps = df["path"][:20] #X
outs = df["sentence"][:20] #Y

X = np.array([LoadAudio("/content/test/cv-corpus-12.0-delta-2022-12-07/en/clips/"+x) for x in tqdm(inps, desc='Loading audio files')])

preds = np.array([transcribe(x) for x in tqdm(X)])

def RMChars(y): # Remove the special charachters
    chars = [
    '!', '#', '$', '%', '&', '(', ')', '*', '+', ',', '-', '.', '/', ':',
    ';', '<', '=', '>', '?', '@', '[', '\\', ']', '^', '_', '`', '{', '|', '}',
    '~', "'", '"'
]
    return ''.join(ch for ch in y if ch not in chars)
preds = np.array([RMChars(x) for x in tqdm(preds)])
outs = np.array([RMChars(x) for x in tqdm(outs)])

import numpy as np
from sklearn.metrics import confusion_matrix

# Split the sentences into individual words
pred_words = [word for pred in preds for word in pred.split()]
out_words = [word for out in outs for word in out.split()]

# Create the confusion matrix
confusion_mat = confusion_matrix(out_words, pred_words)

print(confusion_mat)

import seaborn as sns
import matplotlib.pyplot as plt

normalized_mat = confusion_mat / confusion_mat.sum(axis=1)[:, np.newaxis]
plt.imshow(normalized_mat, cmap='Blues')